services:
  db:
    image: postgres:15-alpine
    container_name: notes-db
    environment:
      POSTGRES_USER: ${DB_USER:-notesuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-notespass}
      POSTGRES_DB: ${DB_NAME:-notesdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-notesuser}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: notes-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-notesdb}
      DB_USER: ${DB_USER:-notesuser}
      DB_PASSWORD: ${DB_PASSWORD:-notespass}
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: notes_postgres_data

networks:
  app-network:
    driver: bridge
    name: notes_network